version: '3'

services:
  scimgateway:
    build: ./scimgateway
    ports:
      - "8884:8884"
    restart: always
    environment:
      loki-new-connector_BASIC_0_USERNAME: luciana
      loki-new-connector_BASIC_0_PASSWORD: admin

    volumes:
      - data:/home/node/app/data
   
  
  
     

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/luciana/Documents/qscim-files/testing/data